#!/bin/bash
# Rhett Applestone

# Check if Jekyll is installed
if ! command -v jekyll &> /dev/null; then
    echo "Jekyll is not installed. Please install Jekyll and try again."
    exit 1
fi

# Check if Micro text editor is installed
if ! command -v micro &> /dev/null; then
    echo "Micro text editor is not installed. Please install Micro and try again."
    exit 1
fi

# Set the Jekyll directory
dir=PUT YOUR DIR HERE

# Change into that dir
cd $dir

# Create the new post
jekyll post "$1"

# Get date as a variable
date=$(date +%Y-%m-%d)

# Open the post in Micro text editor (could be any editor)

micro _posts/"$date"-"$1".md

# Change to the Jekyll dir on exit
cd $dir || exit

# Push changes
git add .
git commit -m "$1"
git push
